### PR TITLE
Add Dockerfile and compose harness

### PR DESCRIPTION
**Pull request by panjacek**
WIP: docker env to run server in docker

Image seems very big, need to work on it to reduce size.

### CODE REVIEW

**Review by carloocchiena — APPROVED** [review]
Thank you for your contribution!

**Comment by carloocchiena** [comment]
@panjacek thank you, I like the idea! 
If you'd finalize the merge I'd like to add you to a new "Contributors" section on the Readme file. Thanks!

**Review by carloocchiena — APPROVED** [review]

**Comment by panjacek** [comment]
I saw pygraphviz depends on graphviz-dev pkg which brings a lot of stuff into docker needed for pip install time only (i think).

But that's something to check later on.

**Comment by carloocchiena** [comment]
yeah thanks Pan, atm pygraphviz is not critical for the pj (used just to print out DB structure)
but let's see how things will evolve
I added your url into the "contributors" section on readme, many thanks!

**Pull request merged**
